CCompiler = gcc
CurrentDirectory = -I.

hellomake: 19050111065.c hellofunc.c
	$(CCompiler) -o hellomake 19050111065.c hellofunc.c $(CurrentDirectory)

deletehellomake:
	rm hellomake

runhellomake:
	./hellomake
